name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout V
        uses: actions/checkout@v4
        with:
          repository: vlang/v
      - name: Checkout C2V
        uses: actions/checkout@v4
        with:
          path: slower_tests

      - name: Build V
        if: runner.os != 'Windows'
        run: make -j4 && ./v symlink
      - name: Build V (Windows)
        if: runner.os == 'Windows'
        run: ./make.bat && ./v symlink

      - name: Run all slower tests
        run: |
          v test slower_tests
